let rank = [
    {
        id: 3,
        imgLink: "",
        fName: "Ahamad Ferdos Sami",
        classRoll: 2301039,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 4,
        imgLink: "",
        fName: "Ahsanul Emon Shezan",
        classRoll: 2301025,
        presentCount: 2,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 5,
        imgLink: "",
        fName: "Aiman Noushin Tithy",
        classRoll: 2301041,
        presentCount: 0,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 6,
        imgLink: "",
        fName: "Anamul Haque",
        classRoll: 2301015,
        presentCount: 0,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 7,
        imgLink: "",
        fName: "Anas Mohammad",
        classRoll: 2301056,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 8,
        imgLink: "",
        fName: "Anik Roy",
        classRoll: 2201058,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 9,
        imgLink: "",
        fName: "Ariful Islam Pavel",
        classRoll: 2301054,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 10,
        imgLink: "",
        fName: "Asma Chowdhury",
        classRoll: 2301068,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 11,
        imgLink: "",
        fName: "Aysha Khanom",
        classRoll: 2301063,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 12,
        imgLink: "",
        fName: "Abdullah Al Mamun",
        classRoll: 0,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 13,
        imgLink: "",
        fName: "Abdullah Hill Kafi",
        classRoll: 2201084,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 14,
        imgLink: "",
        fName: "Hasib",
        classRoll: 2301079,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 15,
        imgLink: "",
        fName: "Hubert Dhrubo Gomes ",
        classRoll: 2301072,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 16,
        imgLink: "",
        fName: "Jenat",
        classRoll: 2201056,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 17,
        imgLink: "",
        fName: "Jion Ibrahim ",
        classRoll: 2301059,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 18,
        imgLink: "",
        fName: "Lamia Hossain Mim",
        classRoll: 2301019,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 19,
        imgLink: "",
        fName: "Muktadur Rahman Shakib",
        classRoll: 2108006,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 20,
        imgLink: "",
        fName: "Madhobi Nag",
        classRoll: 2301060,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 21,
        imgLink: "",
        fName: "Mahmudul Hasan Sakib",
        classRoll: 2301017,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 22,
        imgLink: "",
        fName: "Maimoona ",
        classRoll: 2301008,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 23,
        imgLink: "",
        fName: "Md Arafat hossan",
        classRoll: 2301037,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 24,
        imgLink: "",
        fName: "MD Khaled Hasan",
        classRoll: 2301092,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 25,
        imgLink: "",
        fName: "Md Naeem Sarker",
        classRoll: 2301090,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 26,
        imgLink: "",
        fName: "Md Pranto Hossain Shakib",
        classRoll: 2301098,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 27,
        imgLink: "",
        fName: "Md Rakib Hasan Al Shafi",
        classRoll: 2301114,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 28,
        imgLink: "",
        fName: "Md Robiul Islam ",
        classRoll: 2301108,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 29,
        imgLink: "",
        fName: "Md Toukir Uz Zaman Nirob",
        classRoll: 2301061,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 30,
        imgLink: "",
        fName: "Md Yeasin Ali",
        classRoll: 2301051,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 31,
        imgLink: "",
        fName: "MD. Abir Hossain",
        classRoll: 2301109,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 32,
        imgLink: "",
        fName: "Md. Parvej Hasan",
        classRoll: 2301047,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 33,
        imgLink: "",
        fName: "Md. Rifat dewan",
        classRoll: 2301035,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 34,
        imgLink: "",
        fName: "Md. Sajeeb Sarker",
        classRoll: 2201083,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 35,
        imgLink: "",
        fName: "Md. Sheikh Fardin Shifad ",
        classRoll: 2301065,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 36,
        imgLink: "",
        fName: "Md. Thasin Ahammed",
        classRoll: 2301011,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 37,
        imgLink: "",
        fName: "Md.Tawhidur Rahman Tonmoy",
        classRoll: 2301009,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 38,
        imgLink: "",
        fName: "Md. Mesbha Uddin",
        classRoll: 2301033,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 39,
        imgLink: "",
        fName: "Md. Rakibul Islam",
        classRoll: 2301066,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 40,
        imgLink: "",
        fName: "Meherun Nessa Mim",
        classRoll: 2301096,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 41,
        imgLink: "",
        fName: "Mithila",
        classRoll: 2201064,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 42,
        imgLink: "",
        fName: "Mohammad Al- Nahian",
        classRoll: 2201017,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 43,
        imgLink: "",
        fName: "Mukti Rahman Prova ",
        classRoll: 2301064,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 44,
        imgLink: "",
        fName: "Naeem",
        classRoll: 2301048,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 45,
        imgLink: "",
        fName: "Naibur Rahman Nafis ",
        classRoll: 2301045,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 46,
        imgLink: "",
        fName: "Najifa Bristi ",
        classRoll: 2301069,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 47,
        imgLink: "",
        fName: "Nishat Rumman Prity",
        classRoll: 2301031,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 48,
        imgLink: "",
        fName: "Nusrat Azhari Torey ",
        classRoll: 2301020,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 49,
        imgLink: "",
        fName: "Prapto Kumar Sarker",
        classRoll: 2301104,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 50,
        imgLink: "",
        fName: "Proyon das nejhom",
        classRoll: 2301101,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 51,
        imgLink: "",
        fName: "Rabita Islam",
        classRoll: 2301042,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 52,
        imgLink: "",
        fName: "Rajmin Siraj ",
        classRoll: 2201079,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 53,
        imgLink: "",
        fName: "Rakiul hasan",
        classRoll: 2001003,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 54,
        imgLink: "",
        fName: "Ratul Biswas",
        classRoll: 2301087,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 55,
        imgLink: "",
        fName: "Rohit sen",
        classRoll: 2301036,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 56,
        imgLink: "",
        fName: "Sadia Islam Jannat",
        classRoll: 2301112,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 57,
        imgLink: "",
        fName: "Sajib Hossain Saad",
        classRoll: 2301049,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 58,
        imgLink: "",
        fName: "Sazid Ahmed",
        classRoll: 2201054,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 59,
        imgLink: "",
        fName: "Sazid Al Rafi",
        classRoll: 2201032,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 60,
        imgLink: "",
        fName: "Sumyea Rahman",
        classRoll: 2301013,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 61,
        imgLink: "",
        fName: "Tajmin",
        classRoll: 2301053,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 62,
        imgLink: "",
        fName: "Umme Salma",
        classRoll: 302492,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 63,
        imgLink: "",
        fName: "Yasin Ahmad Abdullah",
        classRoll: 2301001,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 64,
        imgLink: "",
        fName: "Yeakub Hossain Arman",
        classRoll: 2301067,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
    {
        id: 65,
        imgLink: "",
        fName: "Asif Ahmed",
        classRoll: 2201102,
        presentCount: 1,
        contestCount: 0,
        solveCount: 0,
        timeCount: 0,
    },
];

rank.sort ( (a, b) => {
    if( (a.presentCount + a.contestCount) * 10 + a.solveCount*5 > (b.presentCount + b.contestCount) * 10 + b.solveCount*5) {
        return -1;
    }
    else if( ((a.presentCount + a.contestCount) * 10 + a.solveCount*5) < (b.presentCount + b.contestCount) * 10 + b.solveCount*5) {
        return 1;
    }
    else {
        return 0;
    }
});

let i = 0, j = 0;
for(i; i < rank.length; i++) {
    let i_temp_score = (rank[i].presentCount + rank[i].contestCount) * 10 + rank[i].solveCount * 5;
    for(j = i; j < rank.length; j++ ){
        let j_temp_score = (rank[j].presentCount + rank[j].contestCount) * 10 + rank[j].solveCount * 5;
        if (i_temp_score == j_temp_score && (rank[i].timeCount > rank[j].timeCount)) {
            let temp_rank = rank[i];
            rank[i] = rank[j];
            rank[j] = temp_rank;
        }
    }
}

let index = 1;
let tableData = document.getElementById("student-rank");

rank.map((s) => {
    let temp_score = (s.presentCount + s.contestCount) * 10 + s.solveCount * 5;
    let temp = `
        <tr class="card">
            <td>${index++}</td>
            <td>${temp_score}</td>
            <td>${s.fName}</td>
            <td>${s.classRoll}</td>
            <td>${s.presentCount}</td>
            <td>${s.contestCount}</td>
            <td>${s.solveCount}</td>
            <td>${s.timeCount}</td>
        </tr>`;
    tableData.innerHTML = tableData.innerHTML + temp;
    
});




